[book]
authors = ["AbelitoGamer"]
language = "es"
multilingual = false
src = "src"
title = "FunkyPedia"


[output.html]
git-repository-url = "https://github.com/AbelitoGamer/FunkyPedia/tree/main/"
edit-url-template = "https://github.com/AbelitoGamer/FunkyPedia/edit/main/{path}"
